# config.yaml
program: main.py
method: bayes
name: sweep
metric:
  goal: minimize
  name: val_mse
parameters:
  batch_size:
    values: [32, 64, 128, 256, 512, 1024]
  lr:
    min: 0.0001
    max: 0.1
  weight_decay:
    values: [0.0, 1e-6, 1e-5]
  epochs:
    values: [10, 20, 30, 40, 50,70,90,100]
  # optimizer:
  #   values: ['adam', 'adamw']
  seed:
    value: 42
  hidden_dim:
    values: [64, 128, 256, 512, 1024]
  latent:
    value: 8
  num_layers:
    values: [1, 2, 3, 4, 5,6,7,8]
  val_split:
    value: 0.2
  out_dir:
    value: "./checkpoints"